import type {Level,Part,PartType} from "./types";
export const W=1100,H=660,STEP=1/120;
export const kit:Record<PartType,{name:string;w:number;h:number;angle:number;color:string}>={ramp:{name:"Ramp",w:180,h:22,angle:.24,color:"#eac777"},belt:{name:"Conveyor",w:180,h:28,angle:0,color:"#6fa7ac"},spring:{name:"Trampoline",w:110,h:38,angle:.25,color:"#dd806c"},fan:{name:"Fan",w:58,h:68,angle:-Math.PI/2,color:"#7dafbc"},funnel:{name:"Funnel",w:140,h:100,angle:0,color:"#dfb75d"},bumper:{name:"Bumper",w:68,h:68,angle:0,color:"#aa8cbe"},wall:{name:"Bolted wall",w:220,h:28,angle:0,color:"#8c9aa3"},switch:{name:"Corn switch",w:54,h:44,angle:0,color:"#d89065"}};
export const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T; export const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
export const part=(type:PartType,x:number,y:number,angle=kit[type].angle,id=`part-${Math.random().toString(36).slice(2,9)}`):Part=>({id,type,x,y,angle,power:1,flip:1});
const m=(type:PartType,x:number,y:number,angle=0,id:string=type,locked=false,more:Partial<Part>={}):Part=>({...part(type,x,y,angle,id),locked,...more});
const original=[m("ramp",230,210,.24,"ramp-1"),m("belt",418,305,.1,"belt-1"),m("spring",598,468,.25,"spring-1"),m("funnel",860,350,0,"funnel-1"),m("fan",910,452,-Math.PI/2,"fan-1")]; const recipe=(movable:PartType[])=>original.map(p=>({...p,locked:!movable.includes(p.type)}));
type Draft=Omit<Level,"id"|"initial">&{start:(p:Part[])=>void}; const drafts:Draft[]=[
{name:"01 · Special Delivery",tag:"Move the conveyor underneath the inlet.",hint:"Move the conveyor below the inlet, then watch where corn leaves its right end.",sources:[{x:400,y:100,vx:0}],period:.6,bowl:{x:745,y:550},kit:{},solution:[m("belt",470,300,0,"delivery-belt")],start:p=>p[0].x=640},
{name:"02 · The Missing Link",tag:"A gap in the machine. One conveyor in your toolbox.",hint:"Bridge the gap between the wooden ramp and trampoline with the conveyor.",sources:[{x:135,y:95,vx:75}],period:.6,bowl:{x:885,y:548},kit:{belt:1},solution:recipe(["belt"]),start:p=>p.splice(1,1)},
{name:"03 · Over the Wall",tag:"Tilt the trampoline to clear the wall.",hint:"Angle the trampoline toward the right.",sources:[{x:135,y:95,vx:75}],period:.6,bowl:{x:885,y:548},kit:{},solution:[...recipe(["spring"]),m("wall",750,465,Math.PI/2,"wall-1",true)],start:p=>p[2].angle=-.25},
{name:"04 · A Little Breeze",tag:"Use the breeze to carry corn sideways.",hint:"Place the fan up and left of the stream.",sources:[{x:500,y:95,vx:0}],period:.6,bowl:{x:790,y:550},kit:{},solution:[m("fan",320,160,-Math.PI/12,"breeze"),m("funnel",790,415,0,"catcher",true)],start:p=>{p[0].angle=-Math.PI/2;p[0].x=700}},
{name:"05 · Meet in the Middle",tag:"Two inlets. One bucket. Find the meeting point.",hint:"Center the funnel beneath both conveyor ends.",sources:[{x:360,y:100,vx:0},{x:740,y:100,vx:0}],period:1.2,bowl:{x:550,y:550},kit:{},solution:[m("belt",360,240,0,"left-belt",true),m("belt",740,240,0,"right-belt",true,{flip:-1}),m("funnel",550,380,0,"meeting-funnel")],start:p=>p[2].x=720},
{name:"06 · Switchboard Symphony",tag:"Catch each stream with a switch. Both belts reverse together.",hint:"Put the → switch under the left inlet and the ← switch under the right.",sources:[{x:360,y:95,vx:0},{x:740,y:95,vx:0}],period:3,bowl:{x:550,y:550},kit:{},solution:[m("belt",360,270,0,"left-belt",true),m("belt",740,270,0,"right-belt",true),m("funnel",550,410,0,"shared-funnel",true),m("switch",360,175,0,"switch-right",false,{targets:["left-belt","right-belt"],direction:1}),m("switch",740,175,0,"switch-left",false,{targets:["left-belt","right-belt"],direction:-1})],start:p=>{p[3].x=260;p[4].x=840}}];
export const levels:Level[]=drafts.map((d,i)=>{const initial=clone(d.solution);d.start(initial);return{...d,id:["special-delivery","missing-link","over-the-wall","little-breeze","meet-in-the-middle","switchboard-symphony"][i],initial}});
export function normalizeLayout(index:number,input:unknown):Part[]{const l=levels[index];if(!l)return[];const fixed=l.solution.filter(p=>p.locked),mov=l.solution.filter(p=>!p.locked),seen=new Set<string>(),count:Partial<Record<PartType,number>>={},out:Part[]=[];for(const c of Array.isArray(input)?input:[]){if(!c||typeof c!=="object")continue;const p=c as Part;if(!kit[p.type]||typeof p.id!=="string"||seen.has(p.id)||fixed.some(x=>x.id===p.id)||![p.x,p.y,p.angle,p.power,p.flip].every(Number.isFinite))continue;const authored=mov.find(x=>x.id===p.id);if(authored&&authored.type!==p.type)continue;const limit=l.kit[p.type]??mov.filter(x=>x.type===p.type).length;if((count[p.type]??0)>=limit)continue;seen.add(p.id);count[p.type]=(count[p.type]??0)+1;out.push({...p,locked:false,x:clamp(p.x,55,1045),y:clamp(p.y,90,565),power:clamp(p.power,.65,1.5),flip:p.flip<0?-1:1,targets:authored?.targets,direction:authored?.direction})}return[...clone(fixed),...out]}
