export type FurnitureKind =
  | "bookcase"
  | "table"
  | "sofa"
  | "chair"
  | "lamp"
  | "plant"
  | "bed"
  | "basket"
  | "doghouse"
  | "ornament"
  | "bowl"
  | "aquarium"
  | "trampoline";
export interface FurnitureDefinition {
  id: string;
  name: string;
  kind: FurnitureKind;
  width: number;
  depth: number;
  height: number;
  color: number;
  price?: number;
  gameReward?: string;
  description: string;
}
export const furniture: FurnitureDefinition[] = [
  {
    id: "library-shelf",
    name: "Story shelf",
    kind: "bookcase",
    width: 2.4,
    depth: 0.65,
    height: 2.5,
    color: 0x9a6346,
    description: "A home for well-loved stories",
  },
  {
    id: "reading-table",
    name: "Reading table",
    kind: "table",
    width: 2.1,
    depth: 1.2,
    height: 0.9,
    color: 0xb48052,
    description: "A spot to spread out a story",
  },
  {
    id: "sage-sofa",
    name: "Sage sofa",
    kind: "sofa",
    width: 2.3,
    depth: 1,
    height: 1.0,
    color: 0x709b89,
    description: "Soft cushions for daydreams",
  },
  {
    id: "cozy-chair",
    name: "Cozy chair",
    kind: "chair",
    width: 0.8,
    depth: 0.8,
    height: 1.1,
    color: 0xcc9871,
    price: 18,
    description: "Make a matching pair",
  },
  {
    id: "reading-lamp",
    name: "Reading lamp",
    kind: "lamp",
    width: 0.65,
    depth: 0.65,
    height: 1.9,
    color: 0xe8c16f,
    price: 24,
    description: "A little pool of golden light",
  },
  {
    id: "little-fern",
    name: "Little fern",
    kind: "plant",
    width: 0.65,
    depth: 0.65,
    height: 1.0,
    color: 0x5d9977,
    price: 12,
    description: "A leafy friend for your room",
  },
  {
    id: "pet-bowl",
    name: "Sunny pet bowl",
    kind: "bowl",
    width: 0.7,
    depth: 0.7,
    height: 0.26,
    color: 0xe1a45e,
    price: 12,
    description: "Tap to serve a cheerful little meal",
  },
  {
    id: "fish-tank",
    name: "Bubbleglass aquarium",
    kind: "aquarium",
    width: 1.5,
    depth: 0.8,
    height: 1.6,
    color: 0x79b9b5,
    price: 36,
    description: "Three tiny fish make a calm, colorful home",
  },
  {
    id: "pet-trampoline",
    name: "Pet trampoline",
    kind: "trampoline",
    width: 1.3,
    depth: 1.3,
    height: 0.35,
    color: 0xd77872,
    price: 30,
    description: "A springy spot for playful pet hops",
  },
  {
    id: "wish-bed",
    name: "Patchwork dog bed",
    kind: "bed",
    width: 1.5,
    depth: 1.0,
    height: 0.35,
    color: 0xe0a566,
    gameReward: "wishbone-fling:keepsake:bed",
    description: "Wishbone Fling · fourteen throws",
  },
  {
    id: "wish-basket",
    name: "Ball basket",
    kind: "basket",
    width: 0.75,
    depth: 0.75,
    height: 0.7,
    color: 0xc99a65,
    gameReward: "wishbone-fling:keepsake:basket",
    description: "Wishbone Fling · four different toys",
  },
  {
    id: "wish-table",
    name: "Doghouse table",
    kind: "doghouse",
    width: 1.2,
    depth: 1,
    height: 1.15,
    color: 0xc88a62,
    gameReward: "wishbone-fling:keepsake:table",
    description: "Wishbone Fling · all eight toys",
  },
  {
    id: "wildfire-camp-lantern",
    name: "Camp lantern",
    kind: "ornament",
    width: 0.65,
    depth: 0.65,
    height: 0.86,
    color: 0xe4ad52,
    gameReward: "wildfire:camp-lantern",
    description: "Dig & Douse · first fire extinguished",
  },
  ...[
    { id: "sock", name: "Lucky sock", color: 0xe6a15f },
    { id: "squeaker", name: "Squeaky friend", color: 0xdd9079 },
    { id: "bandana", name: "Bandana display", color: 0xd8785c },
    { id: "power-bounce", name: "Bounce Biscuit display", color: 0xe6ac64 },
    { id: "power-magnet", name: "Magnet Bandana display", color: 0x85bdb0 },
    { id: "power-wind", name: "Tailwind Pinwheel display", color: 0xb8a3ce },
  ].map((p) => ({
    id: "wish-" + p.id,
    name: p.name,
    kind: "ornament" as const,
    width: 0.55,
    depth: 0.55,
    height: 0.7,
    color: p.color,
    gameReward: `wishbone-fling:${p.id.startsWith("power-") ? "archive" : "keepsake"}:${p.id}`,
    description: "A special Wishbone Fling keepsake",
  })),
  ...[
    ["brass-key", "Brass key", 0xd6aa56],
    ["mirror-fragment", "Mirror fragment", 0x9ecad2],
    ["passage-lantern", "Passage lantern", 0xf0b75e],
    ["hidden-door-hinge", "Hidden-door hinge", 0xb8894d],
    ["curtain-pull", "Curtain pull", 0xb85d73],
    ["sliding-panel", "Sliding panel", 0x805da7],
    ["optical-prism", "Optical prism", 0x84cbd1],
    ["secret-door-bookcase", "Secret-door bookcase", 0x75513d],
    ["funhouse-map", "Funhouse map", 0xdbc47e],
    ["turning-lock", "Turning lock", 0xc19755],
    ["treasure-latch", "Treasure latch", 0xe0bd68],
    ["miniature-funhouse", "Miniature funhouse", 0xb05279],
  ].map(([id, name, color]) => ({
    id: `funhouse-${id}`,
    name: name as string,
    kind: "ornament" as const,
    width: id === "secret-door-bookcase" ? 0.82 : 0.55,
    depth: 0.42,
    height: id === "secret-door-bookcase" ? 1.05 : 0.7,
    color: color as number,
    gameReward: `pocket-funhouse:${id}`,
    description: "Pocket Funhouse · a tiny room-solving curio",
  })),
  ...[
    ["duet-snow-cushion", "Duet Snow Cushion", 0xbad9e8],
    ["puffin-window-star", "Puffin Window Star", 0xf2cf68],
    ["aurora-wool-rug", "Aurora Wool Rug", 0x79c6b5],
    ["together-pennant", "Together Pennant", 0x648eb4],
  ].map(([id, name, color]) => ({
    id: `arctic-${id}`,
    name: name as string,
    kind: "ornament" as const,
    width: id === "aurora-wool-rug" ? 1.25 : 0.65,
    depth: id === "aurora-wool-rug" ? 0.9 : 0.45,
    height: id === "aurora-wool-rug" ? 0.12 : 0.72,
    color: color as number,
    gameReward: `arctic-duet:${id}`,
    description: "Arctic Duet · a keepsake earned together",
  })),
  ...[
    ["gn-candy-jar", "Candy jar", 0xf1a65c],
    ["gn-gummy-lamp", "Gummy lamp", 0xf3ce62],
    ["gn-sock-cushion", "Soft sock cushion", 0x8dc7b2],
    ["gn-bear-beanbag", "Gummy-bear beanbag", 0xd9788f],
  ].map(([id, name, color]) => ({
    id: id as string,
    name: name as string,
    kind: "ornament" as const,
    width: id === "gn-bear-beanbag" ? 0.9 : 0.62,
    depth: id === "gn-bear-beanbag" ? 0.78 : 0.52,
    height: id === "gn-gummy-lamp" ? 1.05 : 0.68,
    color: color as number,
    gameReward: `gummy-nook:${id}`,
    description: "Gummy Nook · a sweet match-three keepsake",
  })),
  ...[
    ["popcorn-spring-ornament", "Popcorn spring ornament", 0xe2b65d, 0.52],
    ["popcorn-mini-machine", "Mini popcorn machine", 0x587f97, 0.82],
  ].map(([id, name, color, width]) => ({
    id: id as string,
    name: name as string,
    kind: "ornament" as const,
    width: width as number,
    depth: id === "popcorn-mini-machine" ? 0.58 : 0.45,
    height: id === "popcorn-mini-machine" ? 0.95 : 0.68,
    color: color as number,
    gameReward:
      id === "popcorn-mini-machine"
        ? "popcorn:cc-mini-machine"
        : "popcorn:cc-spring-ornament",
    description: "Contraption · a keepsake from a clever popcorn machine",
  })),
  ...[
    ["bureau-night-garden", "Night Garden case", 0x8066a8],
    ["bureau-lanternwing", "Lanternwing case", 0x66a5a7],
  ].map(([id, name, color]) => ({
    id: id as string,
    name: name as string,
    kind: "ornament" as const,
    width: 0.72,
    depth: 0.48,
    height: 0.88,
    color: color as number,
    gameReward: `bureau-after-dark:${String(id).replace("bureau-", "")}`,
    description: "Bureau After Dark · a restored magical archive",
  })),
  ...[
    "Pi",
    "Biscuit",
    "Mochi",
    "Pepper",
    "Clover",
    "Waffles",
    "Nimbus",
    "Fig",
    "Cricket",
    "Maple",
    "Pip",
    "Comet",
  ].map((name, index) => ({
    id: `storm-pup-${index}`,
    name: `${name} rescue-pup figurine`,
    kind: "ornament" as const,
    width: 0.5,
    depth: 0.42,
    height: 0.62,
    color: [0xe6a460, 0xc98570, 0x9cc0bc, 0x788aa8][index % 4],
    gameReward: `stormglide:pup-${index}`,
    description: "Stormglide · a rescued pup keepsake",
  })),
  ...["Mint", "Rose", "Honey", "Lilac", "Ice"].map((name, index) => ({
    id: `storm-trail-${index}`,
    name: `${name} spark light`,
    kind: "ornament" as const,
    width: 0.48,
    depth: 0.38,
    height: 0.8,
    color: [0x72c6ae, 0xdc8495, 0xe8bd62, 0xa68ac7, 0x91cae0][index],
    gameReward: `stormglide:trail-${index}`,
    description: "Stormglide · a glowing spark-trail display",
  })),
  ...[
    ["lantern-token", "Moonlight lantern token", 0xf0b75f],
    ["moon-menu", "Moon menu", 0x6f78aa],
    ["tiny-truck", "Tiny snack truck", 0xd86f58],
  ].map(([id, name, color]) => ({
    id: `mabuhay-${id}`,
    name: name as string,
    kind: "ornament" as const,
    width: id === "tiny-truck" ? 0.82 : 0.58,
    depth: id === "tiny-truck" ? 0.5 : 0.4,
    height: id === "moon-menu" ? 0.82 : 0.62,
    color: color as number,
    gameReward: `moonlight-munch-run:keepsake:${id}`,
    description: "Moonlight Munch Run · a night-market keepsake",
  })),
  {
    id: "veda-leafy-bench",
    name: "Veda’s leafy bench",
    kind: "plant",
    width: 1.35,
    depth: 0.58,
    height: 0.92,
    color: 0x6f9a69,
    gameReward: "vedas-great-escape:leafy-bench",
    description: "Veda’s Great Escape · clear two paths",
  },
  {
    id: "veda-elephant-fountain",
    name: "Veda’s elephant fountain",
    kind: "ornament",
    width: 0.82,
    depth: 0.72,
    height: 0.96,
    color: 0x80a9a3,
    gameReward: "vedas-great-escape:elephant-fountain",
    description: "Veda’s Great Escape · reach the sanctuary",
  },
];
/** Every animated model packaged from Kenney Cube Pets 2.0. Tiger is retained
 * in the local package as the reserved mystery pet, but is deliberately not in
 * the ordinary-pet catalog below. */
export const CUBE_PET_ASSET_KEYS = [
  "beaver",
  "bee",
  "bunny",
  "cat",
  "caterpillar",
  "chick",
  "cow",
  "crab",
  "deer",
  "dog",
  "elephant",
  "fish",
  "fox",
  "giraffe",
  "hog",
  "koala",
  "lion",
  "monkey",
  "panda",
  "parrot",
  "penguin",
  "pig",
  "polar",
  "tiger",
] as const;
export type PetAssetKey = (typeof CUBE_PET_ASSET_KEYS)[number];
export interface PetDefinition {
  id: string;
  name: string;
  color: number;
  accent: number;
  starter: boolean;
  price: number;
  /** The matching packaged Cube Pets GLB and PNG filename stem. */
  assetKey: PetAssetKey;
}
export const pets: PetDefinition[] = [
  // `bunny` is a legacy save ID. Keep it, `cat`, and `fox` stable so Clover,
  // Pip, Fig, and existing ownership continue to load unchanged.
  {
    id: "beaver",
    name: "Bramble the beaver",
    color: 0x9c724e,
    accent: 0xe8c79f,
    starter: false,
    price: 60,
    assetKey: "beaver",
  },
  {
    id: "bee",
    name: "Bumble the bee",
    color: 0xe5b93d,
    accent: 0x4b392d,
    starter: false,
    price: 60,
    assetKey: "bee",
  },
  {
    id: "bunny",
    name: "Pip the bunny",
    color: 0xdcd4c9,
    accent: 0xf5e9d6,
    starter: true,
    price: 60,
    assetKey: "bunny",
  },
  {
    id: "cat",
    name: "Clover the cat",
    color: 0xdec09a,
    accent: 0xf7dfbc,
    starter: true,
    price: 60,
    assetKey: "cat",
  },
  {
    id: "caterpillar",
    name: "Puddle the caterpillar",
    color: 0x8cba65,
    accent: 0xf3dc76,
    starter: false,
    price: 60,
    assetKey: "caterpillar",
  },
  {
    id: "chick",
    name: "Peep the chick",
    color: 0xf5cf54,
    accent: 0xf19b4a,
    starter: false,
    price: 60,
    assetKey: "chick",
  },
  {
    id: "cow",
    name: "Mabel the cow",
    color: 0xf4eee2,
    accent: 0x694e44,
    starter: false,
    price: 60,
    assetKey: "cow",
  },
  {
    id: "crab",
    name: "Coral the crab",
    color: 0xdd7058,
    accent: 0xf4c784,
    starter: false,
    price: 60,
    assetKey: "crab",
  },
  {
    id: "deer",
    name: "Fern the deer",
    color: 0xbd8056,
    accent: 0xf4d0a1,
    starter: false,
    price: 60,
    assetKey: "deer",
  },
  {
    id: "dog",
    name: "Scout the dog",
    color: 0xc38e62,
    accent: 0xf1d2a7,
    starter: false,
    price: 60,
    assetKey: "dog",
  },
  {
    id: "elephant",
    name: "Ellie the elephant",
    color: 0x8c9aa7,
    accent: 0xd7e0e4,
    starter: false,
    price: 60,
    assetKey: "elephant",
  },
  {
    id: "fish",
    name: "Bubbles the fish",
    color: 0x63a8c3,
    accent: 0xf4cb5c,
    starter: false,
    price: 60,
    assetKey: "fish",
  },
  {
    id: "fox",
    name: "Fig the fox",
    color: 0xd88b55,
    accent: 0xffedce,
    starter: false,
    price: 60,
    assetKey: "fox",
  },
  {
    id: "giraffe",
    name: "Sunny the giraffe",
    color: 0xe1aa54,
    accent: 0x825b3c,
    starter: false,
    price: 60,
    assetKey: "giraffe",
  },
  {
    id: "hog",
    name: "Truffle the hog",
    color: 0xe5a5ad,
    accent: 0xf7d3d4,
    starter: false,
    price: 60,
    assetKey: "hog",
  },
  {
    id: "koala",
    name: "Koko the koala",
    color: 0x8b9297,
    accent: 0xf2eee1,
    starter: false,
    price: 60,
    assetKey: "koala",
  },
  {
    id: "lion",
    name: "Leo the lion",
    color: 0xd89443,
    accent: 0x80523a,
    starter: false,
    price: 60,
    assetKey: "lion",
  },
  {
    id: "monkey",
    name: "Mochi the monkey",
    color: 0x986d50,
    accent: 0xedcba2,
    starter: false,
    price: 60,
    assetKey: "monkey",
  },
  {
    id: "panda",
    name: "Bao the panda",
    color: 0xe8e4dc,
    accent: 0x3e4145,
    starter: false,
    price: 60,
    assetKey: "panda",
  },
  {
    id: "parrot",
    name: "Pepper the parrot",
    color: 0x5d9c72,
    accent: 0xe6bd50,
    starter: false,
    price: 60,
    assetKey: "parrot",
  },
  {
    id: "penguin",
    name: "Pebble the penguin",
    color: 0x40546a,
    accent: 0xf4e6c7,
    starter: false,
    price: 60,
    assetKey: "penguin",
  },
  {
    id: "pig",
    name: "Poppy the pig",
    color: 0xeaa5ae,
    accent: 0xf3d0d1,
    starter: false,
    price: 60,
    assetKey: "pig",
  },
  {
    id: "polar",
    name: "Snowdrop the polar bear",
    color: 0xf0eee6,
    accent: 0x91a1aa,
    starter: false,
    price: 60,
    assetKey: "polar",
  },
];
export const getFurniture = (id: string) =>
  furniture.find((item) => item.id === id);
export const getPet = (id: string) => pets.find((pet) => pet.id === id);
