const LEVELS=[
{title:'An elephant-sized entrance',tip:'Push the crate right onto the golden switch. Then head for the flag.',map:['#########','#.......#','#...p...#','#.E.C.TX#','#.......#','#.......#','#########']},
{title:'Room to turn',tip:'You’ll need to get around the crate. Corners are trickier than they look.',map:['#########','#...#..X#','#.p.#.T.#','#...C...#','#..E#...#','#.......#','#########']},
{title:'Two’s a crowd',tip:'Two crates, two switches. Make room before you commit.',map:['#########','#.....TX#','#..C....#','#.#.#...#','#..C..T.#','#E.p....#','#########']},
{title:'The long way round',tip:'The short route isn’t always the right one. Keep a way behind each crate.',map:['#########','#..T#..X#','#.......#','#.C.#.T.#','#...C...#','#E..#p..#','#########']},
{title:'The last gate home',tip:'Three switches stand between Veda and her new home. You’ve got this.',map:['#########','#T....TX#','#..C....#','#..#C#..#','#..C....#','#Ep...T.#','#########']}
];
const DIRS={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]},ARROWS={up:'↑',right:'→',down:'↓',left:'←'};const $=id=>document.getElementById(id);let level=0,game,history=[],done=new Set(),unlocked=0,muted=true,audioCtx,facing=false,hintTimer;const W=9,H=7;const key=(x,y)=>y*W+x;
function parseLevel(l){let g={p:0,boxes:[],walls:[],targets:[],fruit:[],exit:0,moves:0,taken:0};l.map.forEach((row,y)=>[...row].forEach((v,x)=>{let n=key(x,y);if(v==='#')g.walls.push(n);if(v==='E')g.p=n;if(v==='C')g.boxes.push(n);if(v==='T')g.targets.push(n);if(v==='p')g.fruit.push(n);if(v==='X')g.exit=n}));return g}
function isOpen(g){return g.targets.every(n=>g.boxes.includes(n))}
function step(g,dir){const d=DIRS[dir];if(!d)throw Error('Unknown direction');const x=g.p%W+d[0],y=Math.floor(g.p/W)+d[1],n=key(x,y);if(x<0||x>=W||y<0||y>=H||g.walls.includes(n)||n===g.exit&&!isOpen(g))return null;let boxes=[...g.boxes],pushed=false;if(boxes.includes(n)){const bx=x+d[0],by=y+d[1],b=key(bx,by);if(bx<0||bx>=W||by<0||by>=H||g.walls.includes(b)||boxes.includes(b)||b===g.exit)return null;boxes[boxes.indexOf(n)]=b;pushed=true}return {...g,p:n,boxes,moves:g.moves+1,fruit:g.fruit.filter(f=>f!==n),taken:g.taken+(g.fruit.includes(n)?1:0),pushed}}
function solve(g){let queue=[{g,path:[]}],seen=new Set([g.p+'|'+[...g.boxes].sort((a,b)=>a-b)]),i=0;while(i<queue.length&&i<140000){const {g:s,path}=queue[i++];if(s.p===s.exit&&isOpen(s))return path;for(const dir of Object.keys(DIRS)){const n=step(s,dir);if(!n)continue;const k=n.p+'|'+[...n.boxes].sort((a,b)=>a-b);if(seen.has(k))continue;seen.add(k);queue.push({g:n,path:[...path,dir]})}}return null}
function tone(freq=300,duration=.08){if(muted)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.type='sine';o.frequency.value=freq;gain.gain.setValueAtTime(.08,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(gain);gain.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function loadLevel(n){level=n;game=parseLevel(LEVELS[n]);history=[];facing=false;$('win').close();draw(true);message(LEVELS[n].tip)}
function message(s){$('message').textContent=s}
function pos(n){return `left:${n%W/W*100}%;top:${Math.floor(n/W)/H*100}%;`}
function draw(full=false){$('chapter').textContent=`CHAPTER ${String(level+1).padStart(2,'0')} / 05`;$('levelTitle').textContent=LEVELS[level].title;$('peaches').textContent=`🍑 ${game.taken} / ${game.taken+game.fruit.length}`;$('moves').textContent=`${game.moves} moves`;$('undo').disabled=!history.length;$('levels').innerHTML=LEVELS.map((l,i)=>`<button data-level="${i}" title="${l.title}" aria-label="Level ${i+1}: ${l.title}" class="${i===level?'current':done.has(i)?'done':''}" ${i>unlocked?'disabled':''}>${done.has(i)?'✓':i+1}</button>`).join('');const b=$('board');if(full){b.innerHTML=Array.from({length:W*H},(_,n)=>`<div class="tile ${game.walls.includes(n)?'wall':'floor '+((n+Math.floor(n/W))%2?'alt':'')} ${n===game.exit?'exit':''}" id="tile${n}" style="${pos(n)}">${game.targets.includes(n)?'<span class="target">◎</span>':n===game.exit?'<span>🏁</span>':''}</div>`).join('')+game.boxes.map((n,i)=>`<div class="sprite crate" id="box${i}" style="${pos(n)}" aria-label="Crate">📦</div>`).join('')+`<div id="veda" class="sprite player" style="${pos(game.p)}" aria-label="Veda the elephant">🐘</div>`;}
 document.querySelectorAll('.peach').forEach(e=>e.remove());game.fruit.forEach(n=>{const e=document.createElement('span');e.className='peach';e.textContent='🍑';$('tile'+n).append(e)});game.boxes.forEach((n,i)=>{const el=$('box'+i);el.style.cssText=pos(n);el.className='sprite crate'+(game.targets.includes(n)?' parked':'')});$('veda').style.cssText=pos(game.p);$('veda').className='sprite player'+(facing?' left':'');$('tile'+game.exit).classList.toggle('open',isOpen(game));b.setAttribute('aria-label',`Puzzle ${level+1}. Veda at row ${Math.floor(game.p/W)+1}, column ${game.p%W+1}. ${game.boxes.filter(n=>game.targets.includes(n)).length} of ${game.targets.length} switches filled. ${isOpen(game)?'Exit open.':'Exit closed.'}`)}
function move(dir){if($('win').open)return false;document.querySelector('.hint-arrow')?.remove();const next=step(game,dir);if(!next){tone(110,.07);message('No room that way. Try another route, or undo a push.');return false}history.push(JSON.stringify(game));const old=game;game=next;if(dir==='left')facing=true;if(dir==='right')facing=false;draw();tone(game.pushed?190:330,.06);if(game.taken>old.taken){tone(720,.15);message('A peach for the road. Excellent priorities.')}else if(isOpen(game)){message('The gate is open! Follow the flag to the next adventure.')}else if(game.pushed&&game.targets.includes(game.boxes.find(n=>!old.boxes.includes(n)))){tone(550,.15);message('Click! One more switch in place.')}else if(game.pushed){message('Nice push. Remember: Veda can push, but she can’t pull crates.')}else{message(LEVELS[level].tip)}if(game.p===game.exit&&isOpen(game)){done.add(level);unlocked=Math.max(unlocked,Math.min(4,level+1));draw();$('winLabel').textContent=level===4?'WELCOME HOME':'PATH CLEARED';$('winTitle').textContent=level===4?'Room for one more elephant.':'Big elephant. Clever moves.';$('winText').textContent=level===4?`Veda made it to the sanctuary! You solved the final gate in ${game.moves} moves. Sila, Mateo, and Gio are waiting to welcome her home.`:`You found the exit in ${game.moves} moves and collected ${game.taken} of ${game.taken+game.fruit.length} peaches. The next path has a new twist.`;$('continue').textContent=level===4?'Play from the beginning ↻':'Next adventure →';$('win').showModal();tone(880,.3)}return true}
function undo(){if(!history.length)return;$('win').close();game=JSON.parse(history.pop());draw();message('Rewound one move. Try a different angle.')}
function hint(){message('Finding a way through…');setTimeout(()=>{const path=solve(game);if(!path){message('This position is stuck. Undo a few pushes, or restart the level.');return}if(!path.length){message('You’ve already reached the exit. Choose another level to continue.');return}document.querySelector('.hint-arrow')?.remove();const e=document.createElement('span');e.className='hint-arrow';e.textContent=ARROWS[path[0]];$('veda').append(e);message(`Try moving ${path[0]}. A path to the exit is still possible.`);clearTimeout(hintTimer);hintTimer=setTimeout(()=>e.remove(),2400)},30)}
$('undo').onclick=undo;$('restart').onclick=()=>loadLevel(level);$('hint').onclick=hint;$('continue').onclick=()=>loadLevel(level===4?0:level+1);$('stay').onclick=()=>{$('win').close();undo()};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(!muted));tone(440)};$('levels').onclick=e=>{const b=e.target.closest('[data-level]');if(b&&!b.disabled)loadLevel(Number(b.dataset.level))};document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(b.dataset.dir));let lastKey=0;document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase();const dir={arrowup:'up',w:'up',arrowright:'right',d:'right',arrowdown:'down',s:'down',arrowleft:'left',a:'left'}[k];if($('win').open)return;if(dir){e.preventDefault();if(e.repeat&&Date.now()-lastKey<130)return;lastKey=Date.now();move(dir)}else if(k==='z'){e.preventDefault();undo()}else if(k==='r')loadLevel(level);else if(k==='h')hint()});let touch;$('board').addEventListener('pointerdown',e=>{touch=[e.clientX,e.clientY];$('board').setPointerCapture?.(e.pointerId)});$('board').addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch[0],dy=e.clientY-touch[1];touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))>15)move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up')});loadLevel(0);
if(document.modelContext?.registerTool){for(const t of [{name:'read_escape_puzzle',description:'Read the current puzzle layout and elephant position.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({level:level+1,...game})},{name:'move_elephant',description:'Move Veda one tile, pushing a crate when possible.',inputSchema:{type:'object',properties:{direction:{type:'string',enum:Object.keys(DIRS)}},required:['direction'],additionalProperties:false},execute:({direction})=>({moved:move(direction),...game})}])try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{})}catch{}}
