/** Coordinate-free, machine-checked design contracts for campaign rooms 03-20. */
export type RoomSystem = "single-cord" | "two-cord" | "bubble" | "continuous-air" | "tap-air" | "bumper" | "hazard";
export type RequiredMechanic = Readonly<{ kind: "element"; id: string }> | Readonly<{ kind: "prop"; index: number }>;
export type OriginalRoomBrief = Readonly<{
  roomNumber: number; id: string; difficulty: "introductory" | "paired" | "multi-step";
  learningObjective: string;
  /** Every system present in the shipped room, expressed without coordinates. */
  allowedSystems: readonly RoomSystem[];
  /** Systems the zero-ticket route depends on, including its release topology. */
  requiredSystems: readonly RoomSystem[];
  /** Exact taps plus slashes in the checked-in zero-ticket trace. */
  intendedPointerActions: number;
  /** Runtime dependencies individually neutralized by replay tests. */
  requiredMechanics: readonly RequiredMechanic[];
  recovery: string;
}>;

export const ORIGINAL_ROOM_BRIEFS: readonly OriginalRoomBrief[] = Object.freeze([
  { roomNumber: 3, id: "campaign-03-curtain-call", difficulty: "introductory", learningObjective: "Pop, release, then use one rightward bellows cue to reach the offset lock.", allowedSystems: ["single-cord", "bubble", "tap-air"], requiredSystems: ["single-cord", "bubble", "tap-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-3-bellows" }], recovery: "The bellows has a broad force zone and the lock lane remains clear." },
  { roomNumber: 4, id: "campaign-04-whisper-lift", difficulty: "introductory", learningObjective: "Pop and release into a gentle continuous leftward draft.", allowedSystems: ["single-cord", "bubble", "continuous-air", "tap-air"], requiredSystems: ["single-cord", "bubble", "continuous-air"], intendedPointerActions: 2, requiredMechanics: [{ kind: "element", id: "room-4-draft" }], recovery: "The passive draft is gentle; the extra bellows supports the optional ticket return." },
  { roomNumber: 5, id: "campaign-05-draft-mark", difficulty: "introductory", learningObjective: "Recognize a passive rightward draft and release into its lock lane.", allowedSystems: ["single-cord", "bubble", "continuous-air"], requiredSystems: ["single-cord", "bubble", "continuous-air"], intendedPointerActions: 2, requiredMechanics: [{ kind: "element", id: "room-5-draft" }], recovery: "The broad draft zone steadily corrects the descent without a timing tap." },
  { roomNumber: 6, id: "campaign-06-soft-rebound", difficulty: "introductory", learningObjective: "Pop and release onto one large bumper for a safe leftward bank.", allowedSystems: ["single-cord", "bubble", "bumper"], requiredSystems: ["single-cord", "bubble", "bumper"], intendedPointerActions: 2, requiredMechanics: [{ kind: "prop", index: 0 }], recovery: "The bumper is large and the bank opens into a wide lower lock lane." },
  { roomNumber: 7, id: "campaign-07-stage-weight", difficulty: "introductory", learningObjective: "Wait for the cord phase, release, then use one broad leftward bellows beat.", allowedSystems: ["single-cord", "bubble", "tap-air"], requiredSystems: ["single-cord", "bubble", "tap-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-7-ticket-bellows" }], recovery: "The force zone spans the descent and accepts generous release and tap timing." },
  { roomNumber: 8, id: "campaign-08-trapdoor-chalk", difficulty: "introductory", learningObjective: "Use two rightward bellows taps to route around the visible center trapdoor.", allowedSystems: ["single-cord", "bubble", "tap-air", "hazard"], requiredSystems: ["single-cord", "bubble", "tap-air"], intendedPointerActions: 4, requiredMechanics: [{ kind: "element", id: "room-8-bellows" }], recovery: "The narrow striped trapdoor leaves a generous route on either side." },
  { roomNumber: 9, id: "campaign-09-breath-and-buoyancy", difficulty: "paired", learningObjective: "Combine the bubble pop and release with one separated rightward bellows cue.", allowedSystems: ["single-cord", "bubble", "tap-air"], requiredSystems: ["single-cord", "bubble", "tap-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-9-bellows" }], recovery: "The bellows target and force zone are large and separated from the cord." },
  { roomNumber: 10, id: "campaign-10-balcony-bank", difficulty: "paired", learningObjective: "Combine bubble release with a required bumper reversal toward the left lock.", allowedSystems: ["single-cord", "bubble", "bumper"], requiredSystems: ["single-cord", "bubble", "bumper"], intendedPointerActions: 2, requiredMechanics: [{ kind: "prop", index: 0 }], recovery: "The single large bumper creates a shallow, readable bank into open space." },
  { roomNumber: 11, id: "campaign-11-counterweight-cue", difficulty: "paired", learningObjective: "Combine a delayed cord release with one broad rightward bellows beat.", allowedSystems: ["single-cord", "bubble", "tap-air"], requiredSystems: ["single-cord", "bubble", "tap-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-11-ticket-bellows" }], recovery: "The broad force zone keeps the delayed cue comfortably timed." },
  { roomNumber: 12, id: "campaign-12-crosswind-matinee", difficulty: "paired", learningObjective: "Let the continuous wind carry right, then answer with one leftward bellows cue.", allowedSystems: ["single-cord", "bubble", "continuous-air", "tap-air"], requiredSystems: ["single-cord", "bubble", "continuous-air", "tap-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-12-draft" }, { kind: "element", id: "room-12-bellows" }], recovery: "Both force zones are broad, and the correcting bellows opposes the passive drift." },
  { roomNumber: 13, id: "campaign-13-split-velvet", difficulty: "paired", learningObjective: "Release two separated cords and let the passive rightward draft finish the crossing.", allowedSystems: ["two-cord", "bubble", "continuous-air"], requiredSystems: ["two-cord", "bubble", "continuous-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-13-draft" }], recovery: "Either cut order is safe and the key remains suspended until both cuts land." },
  { roomNumber: 14, id: "campaign-14-weighted-wings", difficulty: "paired", learningObjective: "Release two asymmetric cords before answering with one leftward bellows cue.", allowedSystems: ["two-cord", "bubble", "tap-air"], requiredSystems: ["two-cord", "bubble", "tap-air"], intendedPointerActions: 4, requiredMechanics: [{ kind: "element", id: "room-14-bellows" }], recovery: "Either cut order is safe and the bellows zone spans the fall." },
  { roomNumber: 15, id: "campaign-15-orchestra-crossing", difficulty: "multi-step", learningObjective: "Pop, cut both cords, and let the required cross-draft route past the lower pit.", allowedSystems: ["two-cord", "bubble", "continuous-air", "hazard"], requiredSystems: ["two-cord", "bubble", "continuous-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-15-draft" }], recovery: "The passive draft carries the released key away from the isolated pit." },
  { roomNumber: 16, id: "campaign-16-prop-room-passage", difficulty: "multi-step", learningObjective: "Pop, cut both cords, and commit to the required bumper passage into the left lock.", allowedSystems: ["two-cord", "bubble", "bumper"], requiredSystems: ["two-cord", "bubble", "bumper"], intendedPointerActions: 3, requiredMechanics: [{ kind: "prop", index: 0 }], recovery: "The large bumper creates a forgiving bank with open space on the return side." },
  { roomNumber: 17, id: "campaign-17-echoing-flyloft", difficulty: "multi-step", learningObjective: "Pop and cut twice into the loft draft, then counter it with one marked bellows tap.", allowedSystems: ["two-cord", "bubble", "continuous-air", "tap-air"], requiredSystems: ["two-cord", "bubble", "continuous-air", "tap-air"], intendedPointerActions: 4, requiredMechanics: [{ kind: "element", id: "room-17-draft" }, { kind: "element", id: "room-17-bellows" }], recovery: "The opposing air zones are broad and leave a stable central correction lane." },
  { roomNumber: 18, id: "campaign-18-counterweight-chorus", difficulty: "multi-step", learningObjective: "Pop, release both asymmetric cords, and ride the required leftward crosswind past the far hazard.", allowedSystems: ["two-cord", "bubble", "continuous-air", "tap-air", "hazard"], requiredSystems: ["two-cord", "bubble", "continuous-air"], intendedPointerActions: 3, requiredMechanics: [{ kind: "element", id: "room-18-draft" }], recovery: "The hazard stays in the far wing; an optional bellows supports the ticket route." },
  { roomNumber: 19, id: "campaign-19-last-rehearsal", difficulty: "multi-step", learningObjective: "Pop, then make two delayed cuts so the required bumper bank clears the scenery hatch.", allowedSystems: ["two-cord", "bubble", "bumper", "hazard"], requiredSystems: ["two-cord", "bubble", "bumper"], intendedPointerActions: 3, requiredMechanics: [{ kind: "prop", index: 0 }], recovery: "The delayed cuts are consecutive and the large bumper returns the key away from the hatch." },
  { roomNumber: 20, id: "campaign-20-house-lights", difficulty: "multi-step", learningObjective: "Pop, release both cords, and read the first bumper bank between two side hazards.", allowedSystems: ["two-cord", "bubble", "bumper", "hazard"], requiredSystems: ["two-cord", "bubble", "bumper"], intendedPointerActions: 3, requiredMechanics: [{ kind: "prop", index: 0 }], recovery: "Two large banks and a broad center lane keep the side hazards readable and forgiving." },
]);

export const ORIGINAL_ROOM_REQUIRED_MECHANICS: Readonly<Record<string, readonly RequiredMechanic[]>> = Object.freeze(
  Object.fromEntries(ORIGINAL_ROOM_BRIEFS.map((brief) => [brief.id, brief.requiredMechanics])),
);
